var searchData=
[
  ['packet_81',['Packet',['../union_packet.html',1,'']]],
  ['packetcreateroom_82',['PacketCreateRoom',['../struct_packet_create_room.html',1,'']]],
  ['packetdefineusername_83',['PacketDefineUsername',['../struct_packet_define_username.html',1,'']]],
  ['packetfiledatatransfer_84',['PacketFileDataTransfer',['../struct_packet_file_data_transfer.html',1,'']]],
  ['packetfiledownloadrequest_85',['PacketFileDownloadRequest',['../struct_packet_file_download_request.html',1,'']]],
  ['packetfiledownloadvalidation_86',['PacketFileDownloadValidation',['../struct_packet_file_download_validation.html',1,'']]],
  ['packetfiletransfercancel_87',['PacketFileTransferCancel',['../struct_packet_file_transfer_cancel.html',1,'']]],
  ['packetfileuploadrequest_88',['PacketFileUploadRequest',['../struct_packet_file_upload_request.html',1,'']]],
  ['packetfileuploadvalidation_89',['PacketFileUploadValidation',['../struct_packet_file_upload_validation.html',1,'']]],
  ['packetjoin_90',['PacketJoin',['../struct_packet_join.html',1,'']]],
  ['packetjoinroom_91',['PacketJoinRoom',['../struct_packet_join_room.html',1,'']]],
  ['packetleave_92',['PacketLeave',['../struct_packet_leave.html',1,'']]],
  ['packetleaveroom_93',['PacketLeaveRoom',['../struct_packet_leave_room.html',1,'']]],
  ['packetlistrooms_94',['PacketListRooms',['../struct_packet_list_rooms.html',1,'']]],
  ['packetquit_95',['PacketQuit',['../struct_packet_quit.html',1,'']]],
  ['packets_2eh_96',['packets.h',['../packets_8h.html',1,'']]],
  ['packetservererrormessage_97',['PacketServerErrorMessage',['../struct_packet_server_error_message.html',1,'']]],
  ['packetserversuccess_98',['PacketServerSuccess',['../struct_packet_server_success.html',1,'']]],
  ['packettext_99',['PacketText',['../struct_packet_text.html',1,'']]],
  ['packetusernamechanged_100',['PacketUsernameChanged',['../struct_packet_username_changed.html',1,'']]]
];
